### ISSUE TITLE
Players shot while joining the game become invincible

### ISSUE THREAD

**Issue by robhawkes** [robhawkes/rawkets#1]
When a player joins the game they appear in the middle of the map for other players. If the joining player is shot during this time, perhaps before the server has properly set them up, they "die", don't get respawned, and become invincible.

This is easily replicated.

**Comment by robhawkes** [comment]
To fix: Make joining players invincible for a temporary period so they can't be shot at.

**Comment by MrkParsons** [comment]
Yes this happened to me before, at first i just thought i was really good, then i realised something wasn't right when bullets were going right through me and nothing was happening.

**Comment by robhawkes** [comment]
This has been fixed as of 9a208e22bb018cc5d216719cf176ba4ce7dd5e7e
